[package]
name = "stock_app_2"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.9"}
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.15"
regex = "1"